version = 1

[[migrations]]
id = 4264434920377417441
name = "0000_baseline.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 4264434920377417442
name = "0001_workspaces.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 4264434920377417443
name = "0002_api_tokens.sql"
snapshot_name = "0002_snapshot.toml"

[[migrations]]
id = 4264434920377417444
name = "0003_refresh_tokens.sql"
snapshot_name = "0003_snapshot.toml"
